- name: Deploy Nginx on Amazon Linux
  hosts: webservers
  become: true
  collections:
    - amazon.aws

  vars:
    nginx_extras_package_name: nginx1
    nginx_package_name: nginx
    nginx_service_name: nginx
    nginx_html_directory: /usr/share/nginx/html
    nginx_index_file: index.html
    html_content: |
      <!DOCTYPE html>
          <html>
          <head>
              <title>Hello from EC2!</title>
              <style>
                  body { font-family: Arial, sans-serif; background-color: #f0f0f0; text-align: center; padding-top: 50px; }
                  h1 { color: #333; }
                  p { color: #666; }
              </style>
          </head>
          <body>
              <h1>Hello from your EC2 Instance! Now we use variables!</h1>
              <p>This page was deployed by Ansible on Amazon Linux 2.</p>
              <p>Current Time: {{ ansible_date_time.iso8601_micro }}</p>
          </body>
          </html>

  tasks:
    - name: Ensure yum cache is up to date
      ansible.builtin.yum:
        update_cache: yes

    - name: Enable Nginx from Amazon Linux Extras using native command
      ansible.builtin.command: "amazon-linux-extras enable {{ nginx_extras_package_name }}"
      # Note: For 'command' module, variables need to be enclosed in quotes if they are part of a string.

    - name: Install Nginx package
      ansible.builtin.yum:
        name: "{{ nginx_package_name }}"
        state: present

    - name: Ensure Nginx service is running and enabled at boot
      ansible.builtin.service:
        name: "{{ nginx_service_name }}"
        state: started
        enabled: yes

    - name: Deploy a simple index.html page
      ansible.builtin.copy:
        content: "{{ html_content }}"
          
        # Using a combination of directory and file name variables
        dest: "{{ nginx_html_directory }}/{{ nginx_index_file }}"
        mode: '0644'

    - name: Display Nginx service status (for debugging)
      ansible.builtin.command: "systemctl status {{ nginx_service_name }}"
      register: nginx_status_output
      changed_when: false

    - name: Print Nginx service status
      ansible.builtin.debug:
        var: nginx_status_output.stdout_lines