- name: Deploy Nginx on Amazon Linux 2
  hosts: webservers
  become: true
  

  roles:
    - nginx_webserver


  tasks:
    - name: Display Nginx service status (for debugging)
      ansible.builtin.command: "systemctl status nginx" 
      register: nginx_status_output
      changed_when: false

    - name: Print Nginx service status
      ansible.builtin.debug:
        var: nginx_status_output.stdout_lines
