version: 0.0
os: linux

files:
  - source: index.html
    destination: /usr/share/nginx/html
    overwrite: true
file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop: 
    - location: stop_nginx.sh
      timeout: 20 
      runas: root 

  ApplicationStart: 
    - location: start_nginx.sh
      timeout: 20
      runas: root
